### ISSUE TITLE
More Flexibility with GenericEvent trait

### ISSUE THREAD

**Issue by TTWNO** [odilia-app/atspi#149]
The `GenericEvent` trait encodes, what is fundamentally, two separate pieces of functionality.

1. The constants, methods, and types required to `build(...)` the type from its component parts via the AT-SPI protocol.
2. The ability to query `path()`, `sender()` and `body()` types directly.

Although the `body` function may need to be generic over a matching type in a trait describing point 1, perhaps we can find a better abstraction to separate the functionality of these two traits. Here is a basic idea that could be built upon:

```rust
/// Shared behavior of bus `Signal` events.
pub trait GenericEventBuilder<'a> {
  /// The `DBus` member for the event.
  /// For example, for an [`object::TextChangedEvent`] this should be `"TextChanged"`
  const DBUS_MEMBER: &'static str;
  /// The `DBus` interface name for this event.
  /// For example, for any event within [`object`], this should be "org.a11y.atspi.Event.Object".
  const DBUS_INTERFACE: &'static str;
  /// A static match rule string for `DBus`.
  /// This should usually be a string that looks like this: `"type='signal',interface='org.a11y.atspi.Event.Object',member='PropertyChange'"`;
  /// This should be deprecated in favour of composing the string from [`Self::DBUS_MEMBER`] and [`Self::DBUS_INTERFACE`].
  const MATCH_RULE_STRING: &'static str;
  /// A registry event string for registering for event receiving via the `RegistryProxy`.
  /// This should be deprecated in favour of composing the string from [`Self::DBUS_MEMBER`] and [`Self::DBUS_INTERFACE`].
  const REGISTRY_EVENT_STRING: &'static str;

  /// What is the body type of this event.
  type Body: Type + Serialize + Deserialize<'a>;

  /// Build the event from the object pair (`ObjectRef` and the Body).
  /// 
  /// # Errors
  /// 
  /// When the body type, which is what the raw message looks like over `DBus`, does not match the type that is expected for the given event.
  /// It is not possible for this to error on most events, but on events whose raw message [`Self::Body`] type contains a [`enum@zvariant::Value`], you may get errors when constructing the structure.
  fn build(item: ObjectRef, body: Self::Body) -> Result<Self, AtspiError>
  where
    Self: Sized;
}
pub trait GenericEvent: GenericEventBuilder {
  /// Path of the signalling object.
  fn path(&self) -> ObjectPath<'_>;

  /// Sender of the signal.
  /// 
  /// ### Errors
  /// - when deserializing the header failed, or
  /// - When `zbus::get_field!` finds that 'sender' is an invalid field.
  fn sender(&self) -> String;

  /// The body of the object.
  fn body(&self) -> <Self as GenericEventBuilder>::Body;
}

// not syntax checked, just an idea
```

cc @luukvanderduim

**Comment by luukvanderduim** [comment]
Thanks a bunch for starting out this conversation. I feel we have the opportunity to improve things drastically. 
I agree that `GenericEvent` covers distinct functionality sets which makes it a candidate for a split up.

Note that neither of the sketched traits would allow events to be 'addressed' as traits objects, because, as they are drawn, they are not [object safe](https://doc.rust-lang.org/reference/items/traits.html).

The first will never be object safe because for traits to be object safe they cannot have associated consts. There's that.
The latter trait fails because it has a supertrait that is not object safe.

Now this may perhaps be circumvented. We may not need to encode on type level that this trait requires the other to be implemented. I hope we may `assert_impl!` this at build time, but that remains to be seen.

But while we are sketching..

```Rust
pub trait GenericEventBuilder<'a> { ... }
```
This is not a [builder-pattern](https://freemasen.com/blog/phantom-builder/) , though the name resembles one. This makes the trait name confusing in light of common Rust nomenclature.

This trait:
1. Contains a number of properties we´d like the user facing type to have at all time.
2. Offers a way to fallibly convert type from the originating `ObjectRef` and `Body` to the Self type.

How about something along these lines: 

Have a `BusProperties<'a>` wherein we keep the properties, and
a `TryFrom<Message> for EventType` implementation for each type that requires it?

(I know that is a bit different from what `build()` does, but doesn't the `Message` carry both pieces, body and origin object?)

```Rust
/// AT-SPI bus `Signal` events properties.
pub trait BusProperties<'a> {
  /// The `DBus` member for the event.
  /// For example, for an [`object::TextChangedEvent`] this should be `"TextChanged"`
  const DBUS_MEMBER: &'static str;

  /// The `DBus` interface name for this event.
  /// For example, for any event within [`object`], this should be "org.a11y.atspi.Event.Object".
  const DBUS_INTERFACE: &'static str;

  /// A static match rule string for `DBus`.
  /// This should usually be a string that looks like this: `"type='signal',interface='org.a11y.atspi.Event.Object',member='PropertyChange'"`;
  /// This should be deprecated in favour of composing the string from [`Self::DBUS_MEMBER`] and [`Self::DBUS_INTERFACE`].
  const MATCH_RULE_STRING: &'static str;

  /// A registry event string for registering for event receiving via the `RegistryProxy`.
  /// This should be deprecated in favour of composing the string from [`Self::DBUS_MEMBER`] and [`Self::DBUS_INTERFACE`].
  const REGISTRY_EVENT_STRING: &'static str;

  /// What is the body type of this event.
  type Body: Type + Serialize + Deserialize<'a>;
}
```

Maybe we can do a blanket impl. That would be nice. But otherwise we'll just create a macro for the impls.

```Rust 
TryFrom<zbus::Message> for T, where T: BusProperties<'a> + 'a
``` 
to replace the `build()` in the trait?

```Rust
impl_all!(GenericEvent, BusProperties);

pub trait GenericEvent {
  /// Path of the signalling object.
  fn path(&self) -> ObjectPath<'_>;

  /// Sender of the signal.
  /// 
  /// ### Errors
  /// - when deserializing the header failed, or
  /// - When `zbus::get_field!` finds that 'sender' is an invalid field.
  fn sender(&self) -> String;

  /// The body of the object.
  fn body(&self) -> <Self as GenericEventBuilder>::Body;
}
```

Then there are the traits like `HasMember`, `HasInterface` and `HasMatchRule` which only contain a single const.
Can we replace these by the `BusProperties` or vice versa?

Consider this reply a lot of 'thinking out loud' and I hope most of it made sense.

**Comment by TTWNO** [comment]
> blanket impl

Unfortunately, the blanket implementation will not work because [the type T is not guaranteed to be local](https://doc.rust-lang.org/error_codes/E0210.html)

**Comment by TTWNO** [comment]
But I like the idea. It would vastly simplify the `build()` code.
