### ISSUE TITLE
AccessKit Specific Usage

### ISSUE THREAD

**Issue by TTWNO** [odilia-app/atspi#180]
Hi, @DataTriny 

What exactly does `accesskit` need from `atspi`?

I'm curious since we seem to often come to odds with the fact that I want an easier library to maintain (screw the compilation speed), and you (due to downstream `accesskit` usage), want to keep compile times and dependencies low.

Neither perspective is wrong, we just have different use cases for `atspi`.

So, with added context, what _exactly_ does `accesskit` need from `atspi`?
I would happily feature gate half the library if that would make it easier for you to integrate it into `accesskit`, and keep downstream library and application maintainers happy :)
I know both our ideal scenario is that Matt's new Newton protocol catches on, and that reliance on `atspi` will then no-longer be required.
But that is not a given, and I think we should consider making the current situation better if we can.
My primary goal is for both of us to be happy: i.e., I can use some extra libraries, and you can have a lean `atspi` to rely on.
I'm hoping we can come to an agreement on this; please let me know how I can help with that.

Awaiting your response.

**Comment by DataTriny** [comment]
Hello @TTWNO,

You pretty much summarized what AccessKit needs from this crate already:

- Minimal compile times: avoid proc macros,
- Minimal binary size,
- As few dependencies as possible,
- An MSRV policy that make sense,
- API correctness that integrates latest bug fixes and changes from the official AT-SPI protocol.

We will have similar needs to Odilia once we implement integration testing for our Unix adapter since we'll want to simulate an AT-SPI client. Therefore all the work you do in this area is very important, it's just not my priority right now. Still, I want to compile as little code as possible from the client side outside of test builds.

**Comment by TTWNO** [comment]
I was hoping that you could have been more specific, since my intention was to gate a bunch of convenient macro behind a feature flag. I dug into acceeskit myself to find out what pieces of the codebase you use.
