### ISSUE TITLE
How can at-spi2-core notify you about XML changes?

### ISSUE THREAD

**Issue by federicomenaquintero** [odilia-app/atspi#22]
I'm in the process of doing several things more or less at the same time:

* [documenting](https://gitlab.gnome.org/GNOME/at-spi2-core/-/issues/69) the [dbus XML interfaces in at-spi2-core](https://gitlab.gnome.org/GNOME/at-spi2-core/-/tree/main/xml)
* [Fixing incorrect method signatures](https://gitlab.gnome.org/GNOME/at-spi2-core/-/issues/75) as part of [making the XML the single source of truth](https://gitlab.gnome.org/GNOME/at-spi2-core/-/issues/73)

The result is that the dbus XML files in at-spi2-core **are changing** to reflect what the C code actually does.  Bindings that use the XML as a basis will of course want to be notified of this.

So, this issue is me asking you for how to best communicate this.

I can file a bug report here every time I make a change, but this doesn't help other projects (e.g. GTK4, WebKit) that also use DBus directly instead of atk.

(Concretely, my latest fix is in [this commit](https://gitlab.gnome.org/federico/at-spi2-core/-/commit/9096b760c8d8295874c1b1ed37c920634739912b) - not merged yet, hopefully in a merge request soon.)

**Comment by TTWNO** [comment]
Obviously, if you need to notify multiple projects on a consistent basis, then it's going to male sense to make an RSS feed or mailing list with the maintainers' set up as subscribers.

Otherwise, the occasional Github issue would suffice for us.

**Comment by luukvanderduim** [comment]
## notifications
Git hosting services have a well established mechanism to automatically send and receive notifications on a project repository. Developers can subscribe to notifications through the bell icon on the project page. At least both GitHub and GitLab offer such a service.
 
Consider a small repository dedicated to the XML definitions.
- Interested developers should subscribe to this definitions project for notifications on all changes.
- Because only the definitions are kept in this repository, developers would get notified on relevant changes only!
- Projects could then keep a git submodule of the protocol definitions  in their own project repositories. (Such as `libatk`, `Gtk`, `Qt` , ``libatspi` and `atspi`)

###  One ring to rule them all!
I am genuinely excited about the decision to (soon) proclaim the main  XML descriptions the single authoritative definition of AT-SPI2. This likely improves the situation wherein we find ourselves today: 
Interface implementations have often been written by hand, differ between implementers and we may be using introspected definitions of any of these. We cannot have multiple interpretations of a protocol.

The xml definitions will be the single point of truth once implementations (libatk, Gtk, Qt, others) are generated off of these.

### `atspi`
I think (Odiia's) `atspi` took the pragmatic approach by (in part?) using introspected XML descriptions to match what 'is seen in the wild'(?). (Do correct me if I am wrong!)
`atspi` has had - at some point in time - compile time generated interface definitions in a separate, generated crate but currently has statically generated files.

We probably want to keep in sync with the latest official definitions to ensure `atspi` offers the downstream library users the latest, most correct signatures for the signals, method calls and properties known. However this does require that we arrange our project files such that a new set of `zbus` generated traits are quickly and easily swapped in. Currently I think we could  keep those statically generated, but swapping them out should be a breeze.
I have however not quite worked out how `atspi` could cater  `AT`s how to deal with older faulty definitions still used on the bus.

I hope all the above makes sense and/or may serve as food for thought!

**Comment by TTWNO** [comment]
I like @luukvanderduim 's idea.

Would you be open to separating the XML files from the main repo?

Or is there a way to only subcribe to changes in a certain subdirectory of a project on Gitlab?

**Comment by luukvanderduim** [comment]
As far as I know there is no way to:
-  'subscribe to changes of a particular directory' on GitLab
-  git does not allow for 'git submodule a single directory of a repository.'

**Comment by TTWNO** [comment]
Friendly ping @federicomenaquintero , have you found a solution for notifying all maintainers of various a11y projects about XML updates?

I'm happy to just subscribe to and watch `at-spi2-core` updates, but there's a lot of spam watching a whole repo like that. I'm interested enough to be ok with that, but I can not be sure that all other a11y project maintainers will like it.

Your call.

**Comment by federicomenaquintero** [comment]
Replying to @luukvanderduim:
> I think (Odiia's) atspi took the pragmatic approach by (in part?) using introspected XML descriptions to match what 'is seen in the wild'(?). (Do correct me if I am wrong!)

Unfortunately introspecting the XML out of registryd or toolkits has also given outdated info in the past - the script to generate C code with the XML text was not being run as part of the build process; it was a manual thing.

(For lack of `include_str!()` - you how C code needs to jump through some hoops to include random data...)

The current state:

* DBus introspection should give accurate results (it's now in the build process properly and won't go out of date), **except**:
* if one of the `introspect()` implementations has [forgotten to list a particular interface](https://gitlab.gnome.org/GNOME/at-spi2-core/-/commit/8a8941b99fd71f74109e57717e45f69d7cc8a7ca) for an object,
* if the XML interface in question has not been audited yet.

If you generated stuff based on DBus introspection before July 2022, you may want to update again.  I know at least Qt had one such problem.

Replying to @TTWNO:
> Friendly ping @federicomenaquintero , have you found a solution for notifying all maintainers of various a11y projects about XML updates?

Yes, sort of?  [Changes to the DBus XML interfaces](https://gnome.pages.gitlab.gnome.org/at-spi2-core/devel-docs/xml-changes.html) is a newish chapter in at-spi2-core's development guide, and I'll be updating it as the audit proceeds.  Please keep an eye on that page, or maybe it's easier to monitor [the source file](https://gitlab.gnome.org/GNOME/at-spi2-core/-/blob/main/devel-docs/xml-changes.rst) automatically.
