### ISSUE TITLE
`.enabled()` property on StateChangedEvent should be a boolean

### ISSUE THREAD

**Issue by TTWNO** [odilia-app/atspi#45]
Whether the StateChangedEvent contains a boolean or not over the DBus wire, it appears that right now it works with an i32 (DBus: "i") return type.

Should this be manually changed in the `identify.rs` file, then add a test for it returning a boolean, or should we leave it up to the library users figure it out? It's not like checking `==1` is super complicated.

**Comment by luukvanderduim** [comment]
Good question.

I want us to return `bool` but currently that may be unsound interpretation. I think we should ask Federico to make it an explicit `bool`, 'b' in upstream because while we can guess when an `i32` is supposed to represent `true` or `false`, we have no guarantee on what the implementors do - or if every implementor does the same.

**Comment by DataTriny** [comment]
Indeed the `detail1` field is an integer, but as far as I can tell every implementor puts a boolean in here. I think this is a safe assumption. I'd also prefer if the protocol enforced it, but then every signals should be changed.

**Comment by TTWNO** [comment]
https://gitlab.gnome.org/GNOME/at-spi2-core/-/issues/102
