### ISSUE TITLE
AccessibleExt should be cache-transparent

### ISSUE THREAD

**Issue by TTWNO** [odilia-app/atspi#49]
AccessibleExt, and functions like it should contain methods that work on cache or non-cache-enabled versions of `atspi`.
For example, Odilia should be able to use its own caching system to get accessible elements further along in a document, so there should be some way for us to either get the related AccessibleProxy, *or* convert from a caching function/type that can be converted into one.

Then methods like `get_role()` could be run in a cache-transparent manner.

The exact way to do this is unknown, since `Into<AccessibleProxy>` won't work (async call required to create it), and even if we could build one, the AccessibleProxy will not be able to have access to a cache.

Any ideas? We could implement a custom trait like GetFromCache for AccessibleProxy and go from there, but I think there has got to be a better solution.

Speaking of better solutions, @DataTriny , hate to ping you, but how does AccessKit handle its cache? Is there any way that we could have a trait which would give you access to all AccessibleExt functions (and future additions) without the need to directly write your own version of every function?

I'm thinking something like this:

```rust
pub trait AccessibleMaybeCache {
    pub async fn parent() -> impl Accessible;
    pub async fn children() -> Iterator<Item = impl Accessible>;
    pub async fn application() -> impl Accessible;
}
```

I don't think these methods would *need* to be async, so perhaps even use something like `maybe_async`? I'm throwing ideas to the wall here and hoping something sticks. I don't want to force async onto the caching implementation if it works without it.

This way, something like `get_next` could look like: `AccessibleExt::get_next<T: AccessibleMaybeCache>(root: &T, matcher_args: &MatcherArgs, backword: bool);`

Does AccessKit have a function like this already? If so, would it be realistic for it to work with this atspi caching-transparent method, or would you rather just handle it all on your own. I realize AccessKit is quite a larger project than Odilia so I would understand wanting more fine-grained control over your end-product.

(Sorry about the stream-of-consciousness issue here. I'll fix it up later.)

**Comment by luukvanderduim** [comment]
> AccessibleExt, and functions like it should contain methods that work on cache or non-cache-enabled versions of `atspi`. For example, Odilia should be able to use its own caching system to get accessible elements further along in a document, so there should be some way for us to either get the related AccessibleProxy, _or_ convert from a caching function/type that can be converted into one.

So you have these in a `CacheItem`:

```rust
    /// The accessible object (within the application)   (so)
    pub object: (String, OwnedObjectPath),
    /// The application (root object(?)    (so)
    pub app: (String, OwnedObjectPath),
    /// The parent object.  (so)
    pub parent: (String, OwnedObjectPath),
```
Those `(so)` should easily transform into proxies (without async calls, most certainly without RPC calls), so you can call their methods. Is that (part of) what you want?

The `Accessible` type should replace ` (String, OwnedObjectPath)` and we should become its AccessibleProxy without cost.

Then:
- Maybe have method on `CacheItem` that gets n_degree_siblings(n: usize) -> Vec<Accessible> 

Because CacheItem already tells us its own index in the parent, we could easily get  i-n .. i .. i+n objects when receiving a cache object.
I also observed that there is quite a bit overlap between the `AccessibleProxy` interface and the `CacheItem`, so we might be able to have `siblings_n_degree(n: usize) -> Vec<CacheItems>` but that would be more expensive. 
( Again, currently this is non-existent )


> 
> Then methods like `get_role()` could be run in a cache-transparent manner.
> 

Aha! I see what you mean. And this might answer our question: 'Where does the cache belong'. (?)
Method calls should have a cache aware wrapping sibling that looks in the cache first to see if what is requested is already there and otherwise gets it through DBus. 

> The exact way to do this is unknown, since `Into<AccessibleProxy>` won't work (async call required to create it), and even if we could build one, the AccessibleProxy will not be able to have access to a cache.

Maybe cache should be a service provided by atspi.

> 
> Any ideas? We could implement a custom trait like GetFromCache for AccessibleProxy and go from there, but I think there has got to be a better solution.

Accessible's would then implement GetFromCache (or just Cache) which would give them access to such function? That is not a terrible idea even if cahcing were in atspi itself I think. What are the downsides? 

> 
> Speaking of better solutions, @DataTriny , hate to ping you, but how does AccessKit handle its cache? Is there any way that we could have a trait which would give you access to all AccessibleExt functions (and future additions) without the need to directly write your own version of every function?
> 
> I'm thinking something like this:
> 
> ```rust
> pub trait AccessibleMaybeCache {
>     pub async fn parent() -> impl Accessible;
>     pub async fn children() -> Iterator<Item = impl Accessible>;
>     pub async fn application() -> impl Accessible;
> }
> ```
> 
> I don't think these methods would _need_ to be async, so perhaps even use something like `maybe_async`? I'm throwing ideas to the wall here and hoping something sticks. I don't want to force async onto the caching implementation if it works without it.
> 
> This way, something like `get_next` could look like: `AccessibleExt::get_next<T: AccessibleMaybeCache>(root: &T, matcher_args: &MatcherArgs, backword: bool);`
> 
> Does AccessKit have a function like this already? If so, would it be realistic for it to work with this atspi caching-transparent method, or would you rather just handle it all on your own. I realize AccessKit is quite a larger project than Odilia so I would understand wanting more fine-grained control over your end-product.
> 
> (Sorry about the stream-of-consciousness issue here. I'll fix it up later.)

No, no great stuff.

**Comment by DataTriny** [comment]
Hello there.

> how does AccessKit handle its cache? Is there any way that we could have a trait which would give you access to all AccessibleExt functions (and future additions) without the need to directly write your own version of every function?

Currently, AccessKit doesn't implement caching at all. I mean, of course we maintain our own UI tree (that's the whole point of the crate), but the `org.a11y.atspi.Cache` interface have not been implemented.

What is bothering me is that, unlike at-spi2-core, we have to register each interface for every object.

The method/property call flow for an at-spi2-core adapter looks like this:

- Extract the interface,
- Extract the method/property name,
- Route the message to the right interface and method,
- Extract the accessible ID from the path,
- Perform the requested action on the accessible.

In contrast, the flow for AccessKit looks like this:

- Find the relevant object by looking up the path in the object tree,
- Extract the interface,
- Extract the method/property name,
- Call the appropriate method and perform the requested action.

This difference is because of zbus's way of implementing server-side interfaces. In practice this means that we have to walk the UI tree at application startup to register our interfaces and maintain another tree of D-Bus nodes. Implementing the cache will either mean registering and maintaining yet another piece of data for each UI element, or walk the whole UI tree when an AT asks for the cache. If we want to be good AT-SPI citizen, we'll even have to manage another object tree for the private peer-to-peer bus. For rich UI this might represent a significant amount of memory.

So for now my point is: please make sur clients using the atspi crate can deal with providers that don't implement caching, just like at-spi2-core does.

And for the future, maybe we'll want to create our own procedural macro to declare server-side D-Bus interfaces. I still have no idea what it would look like, and how it would deal with introspection for instance.

Hopefully my explanation makes sense.

**Comment by TTWNO** [comment]
> So for now my point is: please make sur clients using the atspi crate can deal with providers that don't implement caching, just like at-spi2-core does.

Understood. Like I said, this would aim to make all methods cache-transparent whether the cache:

1. Does not exist.
2. Eventually exists within the `atspi` crate.
3. Exists outside the crate, like with Odilia.

All cases will be covered, so your crate is safe from sweeping, breaking changes.
