### ISSUE TITLE
Use of unstable rust syntax (let...else)

### ISSUE THREAD

**Issue by francois-caddet** [odilia-app/atspi#61]
# description

When building on NixOs  cargo throw many errors like:

```
error[E0658]: `let...else` statements are unstable
```

From what I saw, all of the `let ... else` are used in a form:

```Rust
let Some(val) = option else { return Err(atspi_error); };
```

# proposed solution.

Prefer to use a stable syntax which in the case of `Option` translation is probably better and not more verbose.
The `let ... else` syntax is provided for cases you expect one variant of an enum and do something else or return a default value. But preferably for enums with more than two variants. 
Moreover, if it's the only reason we need unstable rust channel, it's better to use the stable syntax:

```Rust
let val = option.ok_or(atspi_error)?;
```

# Other solutions

add the `#![feature(let_else)]` in the top lib.rs file.
Anyway as explained above, it's better to avoid using this unstable feature if it's the only case where it's needed and if it's the only unstable feature we need.

# Environment.

NixOS 22.11
rustc 1.64.0

**Comment by TTWNO** [comment]
We always use the latest stable Rust, which is currently 1.67.1. This syntax landed in Rust 1.65.

We will update our minimum rust version in Cargo.toml to reflect this.

**Comment by francois-caddet** [comment]
Ok, I thought it was not already stabilized.
The 1.65 is probably a good MSRV. I was not expecting NixOS stick on that old version of rust.

**Comment by francois-caddet** [comment]
Anyway I personaly prefer the `ok_or` syntax for options ;) but it's only personal feeling

**Comment by luukvanderduim** [comment]
In the end it may be a matter of taste but maybe I can convince you ( a little bit ).

In our example we use it to see whether this is the event we seek, otherwise continue to the next event in stream:

```rust
	while let Some(Ok(ev)) = events.next().await {
		let Ok(change)  = StateChangedEvent::try_from(ev) else { continue };

		if change.kind() == "focused" && change.enabled() == 1 {
			let Some(bus_name) = change.inner().sender()? else { continue };
			println!("Accessible belonging to {bus_name}  focused!");
		}
	}
```
Here it is unambiguous what the pattern, the assignment and the control flow is in case do not match the `Ok(change)` pattern - all in one go.

That being said, I will also keep an eye open for instances where `ok_or` would be more suitable alternative, however I doubt we will lose let-else completely.

Thanks !
